vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /images/salles
            upload_destination: '%kernel.project_dir%/public/images/salles'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
